### ISSUE TITLE
Unable to connect to an Azure AKS cluster

### ISSUE THREAD

**Issue by stevehedrick** [pixel-point/kube-forwarder#15]
Similar to #12, When I attempt to add an AKS cluster kube-forwarder see's my cluster in the config, but fails to connect with a message `Failed to connect to myakscluster cluster(s). Do you want to continue saving?`

If I continue, I can manually add resources, but they won't forward.  If I edit the cluster and choose to test the connection again, it will fail with an 'unauthorized' response.

I believe the issue is that our clusters have Azure authentication enabled.  Essentially we have a user section that looks like this:
```
users:
- name: <username>
  user:
    auth-provider:
      name: azure
      config:
        apiserver-id: <apiserver-app-id>
        client-id: <kubectl-app-id>
        tenant-id: <tenant-id>
```

I'm not sure if the forwarder isn't picking up existing tokens from the kube config file, or if it's attempting to get a new token, and failing at azure's whole go to https://microsoft.com/devicelogin and enter a code demand.

Here's a little background on the Azure authentication: https://docs.giantswarm.io/guides/authenticating-with-microsoft-azure-active-directory/

Really hoping that this works out, as it looks like a really cool and handy tool.
