### ISSUE TITLE
Error while adding AWS cluster created using kube-aws + authenticated with OIDC

### ISSUE THREAD

**Issue by AgrimPrasad** [pixel-point/kube-forwarder#16]
Might be related to #13 which is also about an OIDC authenticated k8s cluster.

1. Installed `kube-forwarder` with `brew cask install kube-forwarder`
1. Upgraded `awscli`: `aws-cli/1.16.200 Python/3.7.4 Darwin/18.6.0 botocore/1.12.190`

Tried to auto-add k8s clusters configured in `~/.kube/config` from the `kube-forwarder` UI, but was unable to do so with errors similar to `ENOENT: no such file or directory, open 'preprod/ca.pem'`

![Screenshot 2019-07-24 at 10 56 39 AM](https://user-images.githubusercontent.com/6386887/61761791-5faf4380-ae02-11e9-9eb7-3c693d11097f.png)

**Comment by lnikell** [comment]
@AgrimPrasad Thank you for your feedback, please download our latest version, we have not updated yet brew cask version of the app.

**Comment by AgrimPrasad** [comment]
@lnikell I just uninstalled the brew cask version, and then reinstalled using this link from the README: https://github.com/pixel-point/kube-forwarder/releases/latest/download/kube-forwarder.dmg

Still saw the same issue, and FWIW, both brew cask and the DMG versions seem to be v1.3.0

![Screenshot 2019-07-25 at 8 56 14 AM](https://user-images.githubusercontent.com/6386887/61838114-76b16c80-aeba-11e9-87e7-ad0005e3f94e.png)

**Comment by lnikell** [comment]
@AgrimPrasad ok it seems that there is an issue with resolving relative paths in production build, we will investigate. For the time being i guess it will help if you change prod/ca.pem to your absolute path something like /home/alex/.kube/prod/ca.pem

**Comment by AgrimPrasad** [comment]
@lnikell Thanks for the update. I've configured the following now in `~/.kube/config`:

```
- cluster:
    certificate-authority: /Users/agrim/.kube/preprod/ca.pem
    server: https://xxx.yyy
  name: preprod
- cluster:
    certificate-authority: /Users/agrim/.kube/prod/ca.pem
    server: https://xxx.yyy
  name: prod
```

However, this time the UI gets stuck on a spinner when `ADD SELECTED CLUSTERS` is clicked:


![Screen Recording 2019-07-26 at 8 49 34 AM mov](https://user-images.githubusercontent.com/6386887/61918341-95c80100-af83-11e9-8e07-878a8d48c922.gif)
