### ISSUE TITLE
Problem connecting to cluster

### ISSUE THREAD

**Issue by nniikkoollaaii** [pixel-point/kube-forwarder#25]
Hello, 

I selected my kubeconfig file and kube-forwarder shows the following error message:

"nodes is forbidden: User "system:anonymous" cannot list nodes at the cluster scope"

my kubeconfig file is:

```
apiVersion: v1
kind: Config
clusters:
- name: caasp
  cluster:
    server: https://my-apiserver:6443
    certificate-authority-data: ...
users:
- name: appenvadmin
  user:
    auth-provider:
      name: oidc
      config:
        client-id: velum
        client-secret: ...
        extra-scopes: groups
        id-token: ...
        idp-certificate-authority-data: ...
        idp-issuer-url: https://my-apiserver:32000
        refresh-token: ...
contexts:
- name: caasp-appenvadmin
  context:
    cluster: caasp
    user: appenvadmin
current-context: caasp-appenvadmin
```

Auth backend is Dex.

Is there a Problem using Kubernetes OIDC Auth?

Thanks for any help!

**Comment by proAlexandr** [comment]
Hi @nniikkoollaaii,
It looks like an issue with the cluster's configuration or a connection configuration. Have you tried to connect to the cluster using kubectl with the same config? Most likely it's not a Kube Forwarder's issue, but if kubectl works, we will investigate it further.

**Comment by nniikkoollaaii** [comment]
Hi @proAlexandr ,

the command 
`kubectl get pods --kubeconfig .\my-kubeconfig`
works. 
So I don't think there is a problem with my connection configuration.

Further investigation would be nice. Thanks!

**Comment by rlopez4** [comment]
I'm having a similar problem with oidc auth-provider. I am able to connect via kubectl but not through kube-forwarder.

**Comment by merktassel** [comment]
I'm experiencing a similar problem with OIDC. `kubectl --context=dev get pods` works fine, but Kube Forwarder displays "Unauthorized" when connecting:

<img width="532" alt="Screen Shot 2019-11-04 at 4 20 04 PM" src="https://user-images.githubusercontent.com/10404365/68162990-01285400-ff1f-11e9-9a7d-e35967a7db46.png">

**Comment by Skymirrh** [comment]
+1 on this, I cannot get Kube Forwarder to work with an OIDC authenticator. All `kubectl` commands (e.g. `kubectl get ns`) work fine, though it should be noted that `myuser` has restricted rights (is only admin of some namespaces, but cannot manage the cluster itself).

### `~/.kube/config`
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority: [redacted]
    server: [redacted]
  name: mycluster
contexts:
- context:
    cluster: mycluster
    user: myuser
  name: mycontext
current-context: mycontext
kind: Config
preferences: {}
users:
- name: myuser
  user:
    auth-provider:
      config:
        client-id: [redacted]
        client-secret: [redacted]
        id-token: [redacted]
        idp-issuer-url: [redacted]
        refresh-token: [redacted]
      name: oidc
```
### Kube Forwarder
![8gDrT7IHh9](https://user-images.githubusercontent.com/4659919/68845000-00d04b80-06cb-11ea-95a5-d8bbf7c85447.gif)
