### ISSUE TITLE
"No active cluster" when attempting to start port forwarding

### ISSUE THREAD

**Issue by vitali-raikov** [pixel-point/kube-forwarder#5]
Hi,

Decided to give this tool a go, I have added cluster through "Create cluster from scratch"
And then just copy pasted cluster config YAML from .kube directory

When attempting to create service
I fill all the fields, I set "Workload type" to deployment and "Workload name" as deployment name and I set the ports to forward from 80 to 1001

However when attempting to start port forwarding it says 
![image](https://user-images.githubusercontent.com/588383/60386939-de83bb80-9aa4-11e9-8186-a434c763a881.png)

The cluster itself is alive and well and deployment with this name exists.
![image](https://user-images.githubusercontent.com/588383/60386945-fb1ff380-9aa4-11e9-86b8-c20b99dbce72.png)

We are running EKS 1.12
macOS High Sierra

What could be the problem?

**Comment by proAlexandr** [comment]
Hi @vitali-raikov, Thank you for the report!
The error appears [here](https://github.com/kubernetes-client/javascript/blob/master/src/config.ts#L287) and means there is something wrong in the config. 
Сould you post your config without secret values here, please? It will help me to figure out what happens, to double check that Kube Forwarder's behaviour is correct and to add a detailed message if it is helpful.
Also, we are going to add a config validation on the creation step (https://github.com/pixel-point/kube-forwarder/issues/4). We're definitely going to improve the error handling message to provide meaningful information.
Thanks!

**Comment by vitali-raikov** [comment]
@proAlexandr Sure, here is the config

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: some_base64_data_here
    server: https://somefakevalue.sk1.eu-west-1.eks.amazonaws.com
  name: staging
contexts:
- context:
    cluster: staging
    namespace: monitoring
    user: staging
  name: staging
current-context: ""
kind: Config
preferences: {}
users:
- name: staging
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - staging
      command: aws-iam-authenticator
      env:
      - name: AWS_PROFILE
        value: default
```

**Comment by proAlexandr** [comment]
Thanks a lot! The problem is that the `current-context` value is empty. You could try to set it to `staging`.
<details>
<summary>The config that works for me</summary>

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: some_base64_data_here
    server: https://somefakevalue.sk1.eu-west-1.eks.amazonaws.com
  name: staging
contexts:
- context:
    cluster: staging
    namespace: monitoring
    user: staging
  name: staging
current-context: "staging"
kind: Config
preferences: {}
users:
- name: staging
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - staging
      command: aws-iam-authenticator
      env:
      - name: AWS_PROFILE
        value: default
```
</details>

We are going to add a context selection dialogue as a part of a task "Support multiple clusters in a config". It will be described as an issue soon.
