### ISSUE TITLE
Forwarding not working but works manually - can you help ?

### ISSUE THREAD

**Issue by iangregsondev** [pixel-point/kube-forwarder#86]
Hi,

I have some forwarding setup - manually, and it works as expected - I am basically listening to a TCP port (its zeromq queue)

```
kubectl port-forward pod/bitcoind-0 --namespace bsv-private-stn 28899:28890
```

On kube forwarder, I have the same setup but its not forwarding correctly, I get a connect event but then the handshake fails. 

![image](https://user-images.githubusercontent.com/2370364/121497519-d3996b80-c9db-11eb-97b8-7e474317a6a5.png)

I am also connecting via HTTP on another port 18332 - and kube forwarder works for this.

I was wondering what the highlighted part means on the UI i.e.

![image](https://user-images.githubusercontent.com/2370364/121497679-faf03880-c9db-11eb-86f3-fc0cb7db92c0.png)

Is it saying that's the only one that's being registered ? I can confirm the 18332 does work - but its just a standard HTTP server - the other ports don't work. Am I doing something wrong ?

Its probably not needed but for clarity, I am pasting my k8s service here - I know the forwarding works on the command line for the port 28899 and I also know the forwarding works within kube-forwarder for a standard HTTP call using port 18332 - which from above is being highlighted for some reason in the kube-forwarder UI.

```
apiVersion: v1
kind: Service
metadata:
  name: bitcoind-0
spec:
  selector:
    statefulset.kubernetes.io/pod-name: bitcoind-0
  ports:
    - name: other
      port: 9333
      protocol: TCP
    - name: rpc
      port: 18332
      protocol: TCP
    - name: zmqpubhashblock
      port: 28890
      protocol: TCP
    - name: zmqpubhashtx
      port: 28891
      protocol: TCP
    - name: zmqpubrawblock
      port: 28892
      protocol: TCP
    - name: zmqpubrawtx
      port: 28893
      protocol: TCP
    - name: pubdiscardedfrommempool
      port: 28894
      protocol: TCP
    - name: pubinvalidtx
      port: 28895
      protocol: TCP
``` 

Any ideas what could be wrong ?
